<?php

/*
 *******************************************************************************************************************
 * Ce fichier a été généré le 2021-06-10 à 17:05:20 en utilisant le script convert_etuSecteurDisciplinaire_from_csv.php.
 * Son contenu est basé sur un export CSV de la table n_secteur_disciplinaire de la BCN datant du 2021-06-10 à 17:00:44.
 *
 * Note : Le script convert_etuSecteurDisciplinaire_from_csv.php est fourni avec les sources du projet LdapSaisie dans
 * le dossier resources/supann.
 *******************************************************************************************************************
 */


$GLOBALS['BCN_SECTEUR_DISCIPLINAIRE'] = array (
  '0' => 'ACCUEIL, HOTELLERIE, TOURISME',
  '1' => 'ADMINISTRATION ECONOMIQUE ET SOCIALE (A.E.S.)',
  '2' => 'AMENAGEMENT',
  '3' => 'ARCHEOLOGIE, ETHNOLOGIE, PREHISTOIRE, ANTHROPOLOGIE',
  '4' => 'ARTS',
  '03' => 'CHIMIE',
  '5' => 'COMMERCE, VENTE',
  '6' => 'CULTURES ET LANGUES REGIONALES',
  '7' => 'ELECTRONIQUE, GENIE ELECTRIQUE, ELECTRON-ELECTROTECH-AUTOMATIQUE (EEA)',
  'AA' => 'En attente d\'attribution',
  '8' => 'FINANCE, BANQUE, ASSURANCE, IMMOBILIER, COMPTABILITE',
  '9' => 'FORMATION GENERALE AUX METIERS DE L\'INGENIEUR',
  '10' => 'FRANCAIS, LANGUE ETRANGERE',
  '11' => 'GENIE CIVIL',
  '12' => 'GENIE DES PROCEDES, MATERIAUX',
  '13' => 'GEOGRAPHIE',
  '14' => 'HISTOIRE',
  '15' => 'INFORMATIQUE',
  '16' => 'INTERDISCIPLINAIRE',
  '17' => 'LANGUES ET LITTERATURES ANCIENNES',
  '18' => 'LANGUES ET LITTERATURES ETRANGERES',
  '19' => 'LANGUES ET LITTERATURES FRANCAISES',
  '20' => 'LANGUES ETRANGERES APPLIQUEES',
  '21' => 'LITTERATURE GENERALE ET COMPAREE',
  '22' => 'MATHEMATIQUE ET INFORMATIQUE',
  '01' => 'MATHEMATIQUES',
  '04' => 'MATHEMATIQUES APPLIQUEES ET SCIENCES SOCIALES (M.A.S.S.)',
  '23' => 'MECANIQUE, GENIE MECANIQUE, INGENIERIE MECANIQUE',
  '07' => 'MEDECINE',
  '08' => 'ODONTOLOGIE',
  '09' => 'PHARMACIE',
  '24' => 'PHILOSOPHIE, EPISTEMOLOGIE',
  '02' => 'PHYSIQUE',
  '25' => 'PHYSIQUE ET CHIMIE',
  '26' => 'PLURI DROIT - SCIENCES ECONOMIQUES - AES',
  '27' => 'PLURI DROIT - SCIENCES POLITIQUES',
  '28' => 'PLURI LANGUES',
  '29' => 'PLURI LETTRES - LANGUES - SC HUMAINES',
  '30' => 'PLURI LETTRES - SCIENCES DU LANGAGE - ARTS',
  '31' => 'PLURI SANTE',
  '32' => 'PLURI SC DE LA VIE, DE LA SANTE, DE LA TERRE ET DE L\'UNIVERS',
  '33' => 'PLURI SCIENCES',
  '34' => 'PLURI SCIENCES ECONOMIQUES ET GESTION',
  '35' => 'PLURI SCIENCES FONDAMENTALES ET APPLICATIONS',
  '36' => 'PLURI SCIENCES HUMAINES ET SOCIALES',
  '37' => 'PSYCHOLOGIE, SCIENCES COGNITIVES',
  '38' => 'RESSOURCES HUMAINES, GESTION DU PERSONNEL ET DE L\'EMPLOI',
  '39' => 'S.T.A.P.S.',
  '-' => 'SANS OBJET',
  '40' => 'SCIENCES DE GESTION',
  '41' => 'SCIENCES DE L\'EDUCATION',
  '42' => 'SCIENCES DE L\'INFORMATION ET LA COMMUNICATION',
  '05' => 'SCIENCES DE L\'UNIVERS, DE LA TERRE, DE L\'ESPACE, DE LA MER',
  '06' => 'SCIENCES DE LA VIE, BIOLOGIE, SANTE',
  '43' => 'SCIENCES DU LANGAGE - LINGUISTIQUE',
  '44' => 'SCIENCES ECONOMIQUES',
  '45' => 'SCIENCES ET TECHNOLOGIE INDUSTRIELLES',
  '46' => 'SCIENCES JURIDIQUES',
  '47' => 'SCIENCES POLITIQUES',
  '48' => 'SCIENCES RELIGIEUSES',
  '49' => 'SOCIOLOGIE, DEMOGRAPHIE',
  '50' => 'THEOLOGIE CATHOLIQUE',
  '51' => 'TRANSPORT, LOGISTIQUE',
  '52' => 'VETERINAIRE',
);
