<?php

/*
 ********************************************************************************************************
 * Ce fichier a été généré le 2021-06-11 à 11:13:39 en utilisant le script convert_supann_type_entite_from_csv.php.
 * Son contenu est basé sur un export CSV des types d'entités fournies par SUPANN au format XLS
 * et datant du 2021-06-10 à 15:29:55.
 *
 * Note : Le script convert_supann_type_entite_from_csv.php est fourni avec les sources du projet LdapSaisie dans
 * le dossier resources/supann.
 ********************************************************************************************************
 */


$GLOBALS['supannTypeEntite'] = array (
  'C000' => 'Bureau du président',
  'C010' => 'Groupement d\'Intérêt Scientifique (GIS)',
  'C020' => 'Aide à la conception de produits pédagogiques',
  'C021' => 'Conception de dispositifs de formation ouverts et à distance',
  'C022' => 'Coordination d\'enseignement transversaux à plusieurs diplômes',
  'C023' => 'Création et mise en place d\'une nouvelle filière',
  'C030' => 'Haut comité éducation économie',
  'C031' => 'Organisation, coordination et suivi pédagogique du tutorat',
  'C032' => 'Participation au développement et à l\'animation de formations délocalisées',
  'C033' => 'Participation aux activités de formation continue',
  'C034' => 'Programmes pluriannuels de formation (PPF)',
  'C035' => 'Organisation, coordination et suivi pédagogique de stage',
  'C050' => 'Plateforme technologique',
  'E101' => 'Conseil d\'Administration (CA)',
  'E102' => 'Section disciplinaire du CA',
  'E103' => 'Conseil Scientifique (CS)',
  'E104' => 'Conseil d\'UFR',
  'E105' => 'Conseil d\'école',
  'E106' => 'Conseil d\'institut',
  'E107' => 'Conseil des Etudes et Vie Universitaire (CEVU)',
  'E108' => 'Conseil de service général universitaire',
  'E109' => 'Conseil de service commun universitaire',
  'E201' => 'Commission Paritaire Etablissement',
  'E202' => 'Commision consultative paritaire',
  'E203' => 'Commission de conseil',
  'E204' => 'Commission des Moyens',
  'E205' => 'Commission des Statuts',
  'E206' => 'Commission Administrative Paritaire',
  'E301' => 'Comité Hygiène et Sécurité',
  'E302' => 'Comité de Pilotage SGI',
  'E303' => 'Comité Technique Paritaire',
  'E304' => 'Comité consultatif',
  'E305' => 'Comité de sélection',
  'E306' => 'Comité de Pilotage SGI',
  'E401' => 'Jury',
  'E801' => 'Conseil CROUS',
  'E901' => 'CNESER (Conseil National de l\'Ens. Sup. Rech.)',
  'E902' => 'CNU Conseil National des Universités',
  'E903' => 'CTPM Comité Tech. Par. Min. Ens. Sup. Rech.',
  'S101' => 'Grand établissement',
  'S102' => 'Université',
  'S103' => 'Institut',
  'S104' => 'École',
  'S105' => 'ENS (Ecole Normale Supérieure)',
  'S106' => 'PRES   (si celui-ci est de type EPSCP) sinon il faudra une catégorie N1-Autre',
  'S107' => 'EFE (Ecole Française de l\'Etranger)',
  'S108' => 'Établissement public administratif rattaché',
  'S109' => 'Observatoire   est-ce un EPSCP? Si oui il faut mettre N1-établissement',
  'S120' => 'Pôle',
  'S200' => 'Composante',
  'S201' => 'UFR',
  'S202' => 'Département',
  'S203' => 'Unité de recherche',
  'S204' => 'Institut',
  'S205' => 'École',
  'S206' => 'Centre polytechnique universitaire',
  'S207' => 'OSU (Observatoire des Sciences de l\'Univers)',
  'S208' => 'IUFM',
  'S220' => 'Structure fédérative de recherche',
  'S221' => 'Collège des écoles doctorales',
  'S222' => 'École doctorale',
  'S230' => 'Service central',
  'S231' => 'Service général',
  'S233' => 'Scolarité',
  'S234' => 'Centre de ressources',
  'S235' => 'Cellule universitaire d\'accueil',
  'S236' => 'Cellule juridique',
  'S237' => 'Cellule controle gestion',
  'S238' => 'Centre',
  'S239' => 'Service culturel et action sociale',
  'S240' => 'Service des Relations Internationales',
  'S241' => 'Service inter-universitaire',
  'S250' => 'SCD',
  'S251' => 'Section-SCD',
  'S252' => 'Formation permanente',
  'S253' => 'SCUIO',
  'S254' => 'SAIC',
  'S255' => 'Autres comme CEP, UEFAPS, …',
  'S256' => 'Service technique',
  'S257' => 'Catégorie prévue dans la loi / peut être appelé "service-commun-rattaché"',
  'S300' => 'Cabinet',
  'S301' => 'Coordination',
  'S302' => 'Division',
  'S304' => 'Mission',
  'S310' => 'Laboratoire',
  'S311' => 'Département de formation',
  'S312' => 'Centre de recherche',
  'S330' => 'Campus',
  'S340' => 'Plate-forme de recherche ou plateau technique',
);
